version: "3"
services:
  flask:
    container_name: flask
    restart: always
    build: ./backend
    ports:
      - "5000:5000"

  angular-app:
    container_name: angular-app
    restart: always
    build: ./angular-app
    ports:
      - "4200:4200"
    links:
      - flask
    depends_on:
      - flask